import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className={"container"}>
      <Head>
        <title>Chess Opening Book</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"main"}>

        <h1 className={"title"}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={"description"}>
          Get started by editing{' '}
          <code className={"code"}>pages/index.tsx</code>
        </p>

        <div className={"grid"}>

            <a href="/dashboard" className={"card"}>
              <h2> Dashboard &rarr;</h2>
                <p>Understand your chess data in a meaningful way</p>
            </a>

            <a href="/GameData/uploadGame" className={"card"}>
              <h2>Game Upload &rarr;</h2>
              <p>Upload a Chess Game (.pgn file), to MongoDB and view your game</p>
            </a>

            <a href="/GameData/showGame" className={"card"}>
              <h2>Chess Game &rarr;</h2>
              <p>View the Chess Board. Which is going to be based off a previous project (In Python)</p>
            </a>

        </div>
      </main>

      <footer className={"footer"}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={"logo"}>
            {/*<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />*/}
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
